service: spaceforedu
image: yurik2718/spaceforedu

servers:
  web:
    - YOUR_VPS_IP # replace with the server's public IP before `kamal setup`

proxy:
  ssl: true
  host: app.spaceforedu.com

registry:
  server: ghcr.io
  username: yurik2718
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

volumes:
  - "spaceforedu_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell:   app exec --interactive --reuse "bash"
  logs:    app logs -f
  dbc:     app exec --interactive --reuse "bin/rails dbconsole --include-password"
